sudo: required
language: node_js
node_js: stable
email:
  on_failure: change
  on_success: never
script: bash ./build.sh
after_success:
- npm run coveralls
env:
  global:
    secure: BfOaUUn4aUeDlZzTevlEwt01jBoz0fEqjLG8anNwI2JEYvr9nh/7Js5xRGnQyFSPu6AXB2ueCgg1855yrU+QNOEl+5NLAv+8t1nhDy3HyjUxE1pn740449beVaU1KKfaDJGYfTAgLEvzPh1p/IwIj5Jzy5kuHQ1za7iSINdhusmje1vFE++a7m2jBG0FUxJMyoiDoY8RpQRC4ZjuEmFPfPe0ia3tBJ70cjJ6ZfQmQdB5hXTXs7jsaXM/pvHL3cLHUlkOtBzNHdBZqNQsnHRJBzDu2pflgvq3lB8cL0yXqbNaUczLICF0ZRgE3TeQg+cpiCGQMW7UkpDgfN+g8KQquoCG+3snhCetdtxOdHdmMFQa0Em64ARKnUwZfAXLzCqLHSsfDD0kJorD+hYbirxhlc84SV6/NUM/4tI8DOcheWj3GT+RcWOYNQyu44cbCzAKWFZfenfgNTMmxs4rjU2ZJ+LjwO48hBSA2Aa5eIx5dQ4T+wc7lIh+UkgM3WNR6cERweJ12LtZ4OR9u0usTDi/oAmI4Wus48rTxMmTSQd8dm+MZWdEaes4oXlHWYGE1fa7JvMfpqeAiw5Koim6VkVCSF6ZbY/nSCJdCXbtHxLsKD8cHCh+ASCS2v2EgsBz01HC9E3zuDg3j4JsnjZY/sqFao0a+8BIOaNA+iHAvl6Nels=
